name 'nginx_node'
maintainer 'Beau LaChance'
maintainer_email 'beau.lachance@gmail.com'
license 'all_rights'
description 'Installs/Configures nginx_node'
long_description 'Installs/Configures nginx_node'
version '0.1.0'

issues_url 'http://www.example.com/issues'
source_url 'http://www.example.com/source'
